package stdr_msgs;

public interface DeleteRobotResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "stdr_msgs/DeleteRobotResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#result definition\nbool success\n";
  boolean getSuccess();
  void setSuccess(boolean value);
}
