package stdr_msgs;

public interface DeleteRobotActionResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "stdr_msgs/DeleteRobotActionResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nDeleteRobotResult result\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  stdr_msgs.DeleteRobotResult getResult();
  void setResult(stdr_msgs.DeleteRobotResult value);
}
