package stdr_msgs;

public interface DeleteRobotActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "stdr_msgs/DeleteRobotActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nDeleteRobotFeedback feedback\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  stdr_msgs.DeleteRobotFeedback getFeedback();
  void setFeedback(stdr_msgs.DeleteRobotFeedback value);
}
