package stdr_msgs;

public interface RegisterRobotGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "stdr_msgs/RegisterRobotGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#goal definition\nstring name\n";
  java.lang.String getName();
  void setName(java.lang.String value);
}
