package stdr_msgs;

public interface RegisterRobotActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "stdr_msgs/RegisterRobotActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nRegisterRobotFeedback feedback\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  stdr_msgs.RegisterRobotFeedback getFeedback();
  void setFeedback(stdr_msgs.RegisterRobotFeedback value);
}
