package stdr_msgs;

public interface RegisterRobotActionGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "stdr_msgs/RegisterRobotActionGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nRegisterRobotGoal goal\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalID getGoalId();
  void setGoalId(actionlib_msgs.GoalID value);
  stdr_msgs.RegisterRobotGoal getGoal();
  void setGoal(stdr_msgs.RegisterRobotGoal value);
}
