package stdr_msgs;

public interface RegisterRobotAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "stdr_msgs/RegisterRobotAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nRegisterRobotActionGoal action_goal\nRegisterRobotActionResult action_result\nRegisterRobotActionFeedback action_feedback\n";
  stdr_msgs.RegisterRobotActionGoal getActionGoal();
  void setActionGoal(stdr_msgs.RegisterRobotActionGoal value);
  stdr_msgs.RegisterRobotActionResult getActionResult();
  void setActionResult(stdr_msgs.RegisterRobotActionResult value);
  stdr_msgs.RegisterRobotActionFeedback getActionFeedback();
  void setActionFeedback(stdr_msgs.RegisterRobotActionFeedback value);
}
