package stdr_msgs;

public interface SpawnRobotResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "stdr_msgs/SpawnRobotResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#result definition\nstdr_msgs/RobotIndexedMsg indexedDescription\nstring message\n";
  stdr_msgs.RobotIndexedMsg getIndexedDescription();
  void setIndexedDescription(stdr_msgs.RobotIndexedMsg value);
  java.lang.String getMessage();
  void setMessage(java.lang.String value);
}
