package kobuki_msgs;

public interface AutoDockingGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "kobuki_msgs/AutoDockingGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#goal\n";
}
