package kobuki_msgs;

public interface AutoDockingFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "kobuki_msgs/AutoDockingFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#feedback\nstring state\nstring text\n\n";
  java.lang.String getState();
  void setState(java.lang.String value);
  java.lang.String getText();
  void setText(java.lang.String value);
}
