package kobuki_msgs;

public interface AutoDockingResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "kobuki_msgs/AutoDockingResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#result\nstring text\n";
  java.lang.String getText();
  void setText(java.lang.String value);
}
