package kobuki_msgs;

public interface AutoDockingActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "kobuki_msgs/AutoDockingActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nAutoDockingFeedback feedback\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  kobuki_msgs.AutoDockingFeedback getFeedback();
  void setFeedback(kobuki_msgs.AutoDockingFeedback value);
}
