package kobuki_msgs;

public interface AutoDockingActionGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "kobuki_msgs/AutoDockingActionGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nAutoDockingGoal goal\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalID getGoalId();
  void setGoalId(actionlib_msgs.GoalID value);
  kobuki_msgs.AutoDockingGoal getGoal();
  void setGoal(kobuki_msgs.AutoDockingGoal value);
}
