package kobuki_msgs;

public interface PowerSystemEvent extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "kobuki_msgs/PowerSystemEvent";
  static final java.lang.String _DEFINITION = "# Power system events\n# This message is generated by important changes in the power system:\n#  - plug/unplug to the docking base or adapter\n#  - transitions to low/critical battery levels\n#  - battery charge completed\n\nuint8 UNPLUGGED           = 0\nuint8 PLUGGED_TO_ADAPTER  = 1\nuint8 PLUGGED_TO_DOCKBASE = 2\nuint8 CHARGE_COMPLETED    = 3\nuint8 BATTERY_LOW         = 4\nuint8 BATTERY_CRITICAL    = 5\n\nuint8 event\n";
  static final byte UNPLUGGED = 0;
  static final byte PLUGGED_TO_ADAPTER = 1;
  static final byte PLUGGED_TO_DOCKBASE = 2;
  static final byte CHARGE_COMPLETED = 3;
  static final byte BATTERY_LOW = 4;
  static final byte BATTERY_CRITICAL = 5;
  byte getEvent();
  void setEvent(byte value);
}
