package rocon_std_msgs;

public interface StringsRequest extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "rocon_std_msgs/StringsRequest";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======\n\nstring data\n";
  java.lang.String getData();
  void setData(java.lang.String value);
}
