package rocon_std_msgs;

public interface StringsPairResponse extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "rocon_std_msgs/StringsPairResponse";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======\n\nuuid_msgs/UniqueID id\nStringsResponse response\n";
  uuid_msgs.UniqueID getId();
  void setId(uuid_msgs.UniqueID value);
  rocon_std_msgs.StringsResponse getResponse();
  void setResponse(rocon_std_msgs.StringsResponse value);
}
