package rocon_std_msgs;

public interface StringsPair extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "rocon_std_msgs/StringsPair";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======\n\nStringsPairRequest pair_request\nStringsPairResponse pair_response\n";
  rocon_std_msgs.StringsPairRequest getPairRequest();
  void setPairRequest(rocon_std_msgs.StringsPairRequest value);
  rocon_std_msgs.StringsPairResponse getPairResponse();
  void setPairResponse(rocon_std_msgs.StringsPairResponse value);
}
