package robotnik_fms_msgs;

public interface PlannerRobotStatus extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "robotnik_fms_msgs/PlannerRobotStatus";
  static final java.lang.String _DEFINITION = "int32 id\ngeometry_msgs/Pose position\nfloat32 battery_voltage\nfloat32 battery_percent\nint32 floor\nint32 node\nstring map\nbool emergency_stop\nint32 mission_id\nint32 mission_percent\nbool idle\nbool charging\nbool elevator_raised\nbool manual\nbool automatic\nbool pick_done\nbool connected\n\nbool waiting_continue_signal\nbool waiting_continue_after_error\nbool waiting_continue_after_cancel\n\nbool alarm_or_error_active\nstring error_msg\n";
  int getId();
  void setId(int value);
  geometry_msgs.Pose getPosition();
  void setPosition(geometry_msgs.Pose value);
  float getBatteryVoltage();
  void setBatteryVoltage(float value);
  float getBatteryPercent();
  void setBatteryPercent(float value);
  int getFloor();
  void setFloor(int value);
  int getNode();
  void setNode(int value);
  java.lang.String getMap();
  void setMap(java.lang.String value);
  boolean getEmergencyStop();
  void setEmergencyStop(boolean value);
  int getMissionId();
  void setMissionId(int value);
  int getMissionPercent();
  void setMissionPercent(int value);
  boolean getIdle();
  void setIdle(boolean value);
  boolean getCharging();
  void setCharging(boolean value);
  boolean getElevatorRaised();
  void setElevatorRaised(boolean value);
  boolean getManual();
  void setManual(boolean value);
  boolean getAutomatic();
  void setAutomatic(boolean value);
  boolean getPickDone();
  void setPickDone(boolean value);
  boolean getConnected();
  void setConnected(boolean value);
  boolean getWaitingContinueSignal();
  void setWaitingContinueSignal(boolean value);
  boolean getWaitingContinueAfterError();
  void setWaitingContinueAfterError(boolean value);
  boolean getWaitingContinueAfterCancel();
  void setWaitingContinueAfterCancel(boolean value);
  boolean getAlarmOrErrorActive();
  void setAlarmOrErrorActive(boolean value);
  java.lang.String getErrorMsg();
  void setErrorMsg(java.lang.String value);
}
