package frontier_exploration;

public interface ExploreTaskAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "frontier_exploration/ExploreTaskAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nExploreTaskActionGoal action_goal\nExploreTaskActionResult action_result\nExploreTaskActionFeedback action_feedback\n";
  frontier_exploration.ExploreTaskActionGoal getActionGoal();
  void setActionGoal(frontier_exploration.ExploreTaskActionGoal value);
  frontier_exploration.ExploreTaskActionResult getActionResult();
  void setActionResult(frontier_exploration.ExploreTaskActionResult value);
  frontier_exploration.ExploreTaskActionFeedback getActionFeedback();
  void setActionFeedback(frontier_exploration.ExploreTaskActionFeedback value);
}
