package frontier_exploration;

public interface ExploreTaskActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "frontier_exploration/ExploreTaskActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nExploreTaskFeedback feedback\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  frontier_exploration.ExploreTaskFeedback getFeedback();
  void setFeedback(frontier_exploration.ExploreTaskFeedback value);
}
