package frontier_exploration;

public interface ExploreTaskResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "frontier_exploration/ExploreTaskResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n";
}
