package frontier_exploration;

public interface ExploreTaskActionResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "frontier_exploration/ExploreTaskActionResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nExploreTaskResult result\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  frontier_exploration.ExploreTaskResult getResult();
  void setResult(frontier_exploration.ExploreTaskResult value);
}
