package frontier_exploration;

public interface ExploreTaskFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "frontier_exploration/ExploreTaskFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#Current target frontier to explore\ngeometry_msgs/PoseStamped next_frontier\n#Current position of robot\ngeometry_msgs/PoseStamped base_position\n\n";
  geometry_msgs.PoseStamped getNextFrontier();
  void setNextFrontier(geometry_msgs.PoseStamped value);
  geometry_msgs.PoseStamped getBasePosition();
  void setBasePosition(geometry_msgs.PoseStamped value);
}
