package frontier_exploration;

public interface ExploreTaskActionGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "frontier_exploration/ExploreTaskActionGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nExploreTaskGoal goal\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalID getGoalId();
  void setGoalId(actionlib_msgs.GoalID value);
  frontier_exploration.ExploreTaskGoal getGoal();
  void setGoal(frontier_exploration.ExploreTaskGoal value);
}
