package robotnik_msgs;

public interface SetElevatorGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "robotnik_msgs/SetElevatorGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\nElevatorAction action\n";
  robotnik_msgs.ElevatorAction getAction();
  void setAction(robotnik_msgs.ElevatorAction value);
}
