package robotnik_msgs;

public interface SetElevatorFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "robotnik_msgs/SetElevatorFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\nElevatorStatus status\n\n";
  robotnik_msgs.ElevatorStatus getStatus();
  void setStatus(robotnik_msgs.ElevatorStatus value);
}
