package robotnik_msgs;

public interface SetElevatorResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "robotnik_msgs/SetElevatorResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\nbool result\nElevatorStatus status\n";
  boolean getResult();
  void setResult(boolean value);
  robotnik_msgs.ElevatorStatus getStatus();
  void setStatus(robotnik_msgs.ElevatorStatus value);
}
