package object_recognition_msgs;

public interface ObjectRecognitionResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "object_recognition_msgs/ObjectRecognitionResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n# Send the found objects, see the msg files for docs\nobject_recognition_msgs/RecognizedObjectArray recognized_objects\n";
  object_recognition_msgs.RecognizedObjectArray getRecognizedObjects();
  void setRecognizedObjects(object_recognition_msgs.RecognizedObjectArray value);
}
