package moveit_msgs;

public interface ExecuteTrajectoryAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "moveit_msgs/ExecuteTrajectoryAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nExecuteTrajectoryActionGoal action_goal\nExecuteTrajectoryActionResult action_result\nExecuteTrajectoryActionFeedback action_feedback\n";
  moveit_msgs.ExecuteTrajectoryActionGoal getActionGoal();
  void setActionGoal(moveit_msgs.ExecuteTrajectoryActionGoal value);
  moveit_msgs.ExecuteTrajectoryActionResult getActionResult();
  void setActionResult(moveit_msgs.ExecuteTrajectoryActionResult value);
  moveit_msgs.ExecuteTrajectoryActionFeedback getActionFeedback();
  void setActionFeedback(moveit_msgs.ExecuteTrajectoryActionFeedback value);
}
