package moveit_msgs;

public interface PickupActionResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "moveit_msgs/PickupActionResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nPickupResult result\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  moveit_msgs.PickupResult getResult();
  void setResult(moveit_msgs.PickupResult value);
}
