package moveit_msgs;

public interface PlaceAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "moveit_msgs/PlaceAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nPlaceActionGoal action_goal\nPlaceActionResult action_result\nPlaceActionFeedback action_feedback\n";
  moveit_msgs.PlaceActionGoal getActionGoal();
  void setActionGoal(moveit_msgs.PlaceActionGoal value);
  moveit_msgs.PlaceActionResult getActionResult();
  void setActionResult(moveit_msgs.PlaceActionResult value);
  moveit_msgs.PlaceActionFeedback getActionFeedback();
  void setActionFeedback(moveit_msgs.PlaceActionFeedback value);
}
