package moveit_msgs;

public interface PlaceActionGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "moveit_msgs/PlaceActionGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nPlaceGoal goal\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalID getGoalId();
  void setGoalId(actionlib_msgs.GoalID value);
  moveit_msgs.PlaceGoal getGoal();
  void setGoal(moveit_msgs.PlaceGoal value);
}
