package rocon_service_pair_msgs;

public interface TestiesResponse extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "rocon_service_pair_msgs/TestiesResponse";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======\nuuid_msgs/UniqueID id\nstring data\n";
  uuid_msgs.UniqueID getId();
  void setId(uuid_msgs.UniqueID value);
  java.lang.String getData();
  void setData(java.lang.String value);
}
