package twist_mux_msgs;

public interface JoyPriorityActionResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "twist_mux_msgs/JoyPriorityActionResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nJoyPriorityResult result\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  twist_mux_msgs.JoyPriorityResult getResult();
  void setResult(twist_mux_msgs.JoyPriorityResult value);
}
