package twist_mux_msgs;

public interface JoyPriorityAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "twist_mux_msgs/JoyPriorityAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nJoyPriorityActionGoal action_goal\nJoyPriorityActionResult action_result\nJoyPriorityActionFeedback action_feedback\n";
  twist_mux_msgs.JoyPriorityActionGoal getActionGoal();
  void setActionGoal(twist_mux_msgs.JoyPriorityActionGoal value);
  twist_mux_msgs.JoyPriorityActionResult getActionResult();
  void setActionResult(twist_mux_msgs.JoyPriorityActionResult value);
  twist_mux_msgs.JoyPriorityActionFeedback getActionFeedback();
  void setActionFeedback(twist_mux_msgs.JoyPriorityActionFeedback value);
}
