package twist_mux_msgs;

public interface JoyTurboAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "twist_mux_msgs/JoyTurboAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nJoyTurboActionGoal action_goal\nJoyTurboActionResult action_result\nJoyTurboActionFeedback action_feedback\n";
  twist_mux_msgs.JoyTurboActionGoal getActionGoal();
  void setActionGoal(twist_mux_msgs.JoyTurboActionGoal value);
  twist_mux_msgs.JoyTurboActionResult getActionResult();
  void setActionResult(twist_mux_msgs.JoyTurboActionResult value);
  twist_mux_msgs.JoyTurboActionFeedback getActionFeedback();
  void setActionFeedback(twist_mux_msgs.JoyTurboActionFeedback value);
}
