package twist_mux_msgs;

public interface JoyTurboGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "twist_mux_msgs/JoyTurboGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n";
}
