package twist_mux_msgs;

public interface JoyTurboActionGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "twist_mux_msgs/JoyTurboActionGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nJoyTurboGoal goal\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalID getGoalId();
  void setGoalId(actionlib_msgs.GoalID value);
  twist_mux_msgs.JoyTurboGoal getGoal();
  void setGoal(twist_mux_msgs.JoyTurboGoal value);
}
