package yocs_msgs;

public interface DockingInteractorAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "yocs_msgs/DockingInteractorAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nDockingInteractorActionGoal action_goal\nDockingInteractorActionResult action_result\nDockingInteractorActionFeedback action_feedback\n";
  yocs_msgs.DockingInteractorActionGoal getActionGoal();
  void setActionGoal(yocs_msgs.DockingInteractorActionGoal value);
  yocs_msgs.DockingInteractorActionResult getActionResult();
  void setActionResult(yocs_msgs.DockingInteractorActionResult value);
  yocs_msgs.DockingInteractorActionFeedback getActionFeedback();
  void setActionFeedback(yocs_msgs.DockingInteractorActionFeedback value);
}
