package yocs_msgs;

public interface DockingInteractorActionResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "yocs_msgs/DockingInteractorActionResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nDockingInteractorResult result\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  yocs_msgs.DockingInteractorResult getResult();
  void setResult(yocs_msgs.DockingInteractorResult value);
}
