package yocs_msgs;

public interface DockingInteractorFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "yocs_msgs/DockingInteractorFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n# Feedback\nint8 level\n\nint8 DEBUG=1\nint8 INFO=2\nint8 WARN=4\nint8 ERROR=8\n\nstring message\n\n";
  static final byte DEBUG = 1;
  static final byte INFO = 2;
  static final byte WARN = 4;
  static final byte ERROR = 8;
  byte getLevel();
  void setLevel(byte value);
  java.lang.String getMessage();
  void setMessage(java.lang.String value);
}
