package yocs_msgs;

public interface DockingInteractorActionGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "yocs_msgs/DockingInteractorActionGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nDockingInteractorGoal goal\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalID getGoalId();
  void setGoalId(actionlib_msgs.GoalID value);
  yocs_msgs.DockingInteractorGoal getGoal();
  void setGoal(yocs_msgs.DockingInteractorGoal value);
}
