package yocs_msgs;

public interface DockingInteractorGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "yocs_msgs/DockingInteractorGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n# Request\nint8 command\nfloat32 distance\n\nint8 WAKE_UP= 10\nint8 REGISTER_DOCK_IN_GLOBAL_FRAME = 20\nint8 RETURN_TO_DOCK = 30\nint8 GOTO_DOCK_FRONT = 40\nint8 CALL_AUTODOCK = 50\n";
  static final byte WAKE_UP = 10;
  static final byte REGISTER_DOCK_IN_GLOBAL_FRAME = 20;
  static final byte RETURN_TO_DOCK = 30;
  static final byte GOTO_DOCK_FRONT = 40;
  static final byte CALL_AUTODOCK = 50;
  byte getCommand();
  void setCommand(byte value);
  float getDistance();
  void setDistance(float value);
}
