package yocs_msgs;

public interface LocalizeActionGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "yocs_msgs/LocalizeActionGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nLocalizeGoal goal\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalID getGoalId();
  void setGoalId(actionlib_msgs.GoalID value);
  yocs_msgs.LocalizeGoal getGoal();
  void setGoal(yocs_msgs.LocalizeGoal value);
}
