package yocs_msgs;

public interface LocalizeFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "yocs_msgs/LocalizeFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\nstring message\n\n";
  java.lang.String getMessage();
  void setMessage(java.lang.String value);
}
