package yocs_msgs;

public interface LocalizeAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "yocs_msgs/LocalizeAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nLocalizeActionGoal action_goal\nLocalizeActionResult action_result\nLocalizeActionFeedback action_feedback\n";
  yocs_msgs.LocalizeActionGoal getActionGoal();
  void setActionGoal(yocs_msgs.LocalizeActionGoal value);
  yocs_msgs.LocalizeActionResult getActionResult();
  void setActionResult(yocs_msgs.LocalizeActionResult value);
  yocs_msgs.LocalizeActionFeedback getActionFeedback();
  void setActionFeedback(yocs_msgs.LocalizeActionFeedback value);
}
