package yocs_msgs;

public interface LocalizeGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "yocs_msgs/LocalizeGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\nint8 command\nfloat32 distortion\n\nint8 STAND_AND_LOCALIZE=10\nint8 SPIN_AND_LOCALIZE =20\n";
  static final byte STAND_AND_LOCALIZE = 10;
  static final byte SPIN_AND_LOCALIZE = 20;
  byte getCommand();
  void setCommand(byte value);
  float getDistortion();
  void setDistortion(float value);
}
