package yocs_msgs;

public interface NavigateToAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "yocs_msgs/NavigateToAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nNavigateToActionGoal action_goal\nNavigateToActionResult action_result\nNavigateToActionFeedback action_feedback\n";
  yocs_msgs.NavigateToActionGoal getActionGoal();
  void setActionGoal(yocs_msgs.NavigateToActionGoal value);
  yocs_msgs.NavigateToActionResult getActionResult();
  void setActionResult(yocs_msgs.NavigateToActionResult value);
  yocs_msgs.NavigateToActionFeedback getActionFeedback();
  void setActionFeedback(yocs_msgs.NavigateToActionFeedback value);
}
