package yocs_msgs;

public interface NavigateToGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "yocs_msgs/NavigateToGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n# Goal\nstring location\nint8   approach_type\nint8   num_retry\nfloat32 timeout\n\n# This variable used when approach near is requested\nfloat32 distance\n\nint8 APPROACH_NEAR = 11\nint8 APPROACH_ON   = 12\n";
  static final byte APPROACH_NEAR = 11;
  static final byte APPROACH_ON = 12;
  java.lang.String getLocation();
  void setLocation(java.lang.String value);
  byte getApproachType();
  void setApproachType(byte value);
  byte getNumRetry();
  void setNumRetry(byte value);
  float getTimeout();
  void setTimeout(float value);
  float getDistance();
  void setDistance(float value);
}
