package yocs_msgs;

public interface NavigateToResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "yocs_msgs/NavigateToResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n# Result\nbool    success\nfloat32 distance\nstring  message\n";
  boolean getSuccess();
  void setSuccess(boolean value);
  float getDistance();
  void setDistance(float value);
  java.lang.String getMessage();
  void setMessage(java.lang.String value);
}
