package robotnik_navigation_msgs;

public interface DockResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "robotnik_navigation_msgs/DockResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n# result\nbool success\n";
  boolean getSuccess();
  void setSuccess(boolean value);
}
