package robotnik_navigation_msgs;

public interface MoveFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "robotnik_navigation_msgs/MoveFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n# feedback\ngeometry_msgs/Pose2D remaining\ngeometry_msgs/Twist current_velocity\n\n\n";
  geometry_msgs.Pose2D getRemaining();
  void setRemaining(geometry_msgs.Pose2D value);
  geometry_msgs.Twist getCurrentVelocity();
  void setCurrentVelocity(geometry_msgs.Twist value);
}
