package robotnik_navigation_msgs;

public interface MoveAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "robotnik_navigation_msgs/MoveAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nMoveActionGoal action_goal\nMoveActionResult action_result\nMoveActionFeedback action_feedback\n";
  robotnik_navigation_msgs.MoveActionGoal getActionGoal();
  void setActionGoal(robotnik_navigation_msgs.MoveActionGoal value);
  robotnik_navigation_msgs.MoveActionResult getActionResult();
  void setActionResult(robotnik_navigation_msgs.MoveActionResult value);
  robotnik_navigation_msgs.MoveActionFeedback getActionFeedback();
  void setActionFeedback(robotnik_navigation_msgs.MoveActionFeedback value);
}
