package franka_control;

public interface ErrorRecoveryAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_control/ErrorRecoveryAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nErrorRecoveryActionGoal action_goal\nErrorRecoveryActionResult action_result\nErrorRecoveryActionFeedback action_feedback\n";
  franka_control.ErrorRecoveryActionGoal getActionGoal();
  void setActionGoal(franka_control.ErrorRecoveryActionGoal value);
  franka_control.ErrorRecoveryActionResult getActionResult();
  void setActionResult(franka_control.ErrorRecoveryActionResult value);
  franka_control.ErrorRecoveryActionFeedback getActionFeedback();
  void setActionFeedback(franka_control.ErrorRecoveryActionFeedback value);
}
