package franka_control;

public interface ErrorRecoveryResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_control/ErrorRecoveryResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n";
}
