package franka_gripper;

public interface GraspAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_gripper/GraspAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nGraspActionGoal action_goal\nGraspActionResult action_result\nGraspActionFeedback action_feedback\n";
  franka_gripper.GraspActionGoal getActionGoal();
  void setActionGoal(franka_gripper.GraspActionGoal value);
  franka_gripper.GraspActionResult getActionResult();
  void setActionResult(franka_gripper.GraspActionResult value);
  franka_gripper.GraspActionFeedback getActionFeedback();
  void setActionFeedback(franka_gripper.GraspActionFeedback value);
}
