package franka_gripper;

public interface HomingResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_gripper/HomingResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\nbool success\nstring error\n";
  boolean getSuccess();
  void setSuccess(boolean value);
  java.lang.String getError();
  void setError(java.lang.String value);
}
