package franka_gripper;

public interface HomingAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_gripper/HomingAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHomingActionGoal action_goal\nHomingActionResult action_result\nHomingActionFeedback action_feedback\n";
  franka_gripper.HomingActionGoal getActionGoal();
  void setActionGoal(franka_gripper.HomingActionGoal value);
  franka_gripper.HomingActionResult getActionResult();
  void setActionResult(franka_gripper.HomingActionResult value);
  franka_gripper.HomingActionFeedback getActionFeedback();
  void setActionFeedback(franka_gripper.HomingActionFeedback value);
}
