package franka_gripper;

public interface HomingGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_gripper/HomingGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n";
}
