package franka_gripper;

public interface MoveGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_gripper/MoveGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\nfloat64 width  # [m]\nfloat64 speed  # [m/s]\n";
  double getWidth();
  void setWidth(double value);
  double getSpeed();
  void setSpeed(double value);
}
