package franka_gripper;

public interface StopGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_gripper/StopGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n";
}
