package franka_gripper;

public interface StopActionResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_gripper/StopActionResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nStopResult result\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  franka_gripper.StopResult getResult();
  void setResult(franka_gripper.StopResult value);
}
