package franka_gripper;

public interface StopAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_gripper/StopAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nStopActionGoal action_goal\nStopActionResult action_result\nStopActionFeedback action_feedback\n";
  franka_gripper.StopActionGoal getActionGoal();
  void setActionGoal(franka_gripper.StopActionGoal value);
  franka_gripper.StopActionResult getActionResult();
  void setActionResult(franka_gripper.StopActionResult value);
  franka_gripper.StopActionFeedback getActionFeedback();
  void setActionFeedback(franka_gripper.StopActionFeedback value);
}
